import "./capitalization.test.js";
import "./dom-construction.test.js";
import "./dom-traversal.test.js";
import "./excluded-domains.test.js";
import "./pronoun-replacement.test.js";
import "./stopword-highlights.test.js";
import "./verb-pluralization.test.js";
import "./word-replacement.test.js";
import "./grammar/test-runner.js";
